import { NextRequest, NextResponse } from "next/server";
import { OpenAI } from "openai";
import { fetchVercelBuildLogs } from "@/lib/vercel-api";
import { fetchGitHubFileContents, createFixPullRequest } from "@/lib/github-api";

// Allow 60 seconds because diagnosing and patching codebase takes time
export const maxDuration = 60;

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(req: NextRequest) {
    try {
        const payload = await req.json();

        // 1. Verify this is a Vercel Webhook Deployment Error event
        if (payload.type !== "deployment.error") {
            return NextResponse.json({ message: "Ignored event type." }, { status: 200 });
        }

        const deploymentId = payload.payload?.deployment?.id;
        if (!deploymentId) {
            return NextResponse.json({ error: "Missing deployment ID" }, { status: 400 });
        }

        console.log(`🚨 Vercel Guardian: Caught build failure on deployment ${deploymentId}`);

        // 2. Fetch the raw build logs from Vercel REST API
        const buildLogs = await fetchVercelBuildLogs(deploymentId);
        
        // 3. LLM Step 1: Diagnose which file is broken
        console.log("🕵️ Vercel Guardian: Diagnosing offending file...");
        const pathDiagnosis = await openai.chat.completions.create({
            model: "gpt-4o",
            response_format: { type: "json_object" },
            messages: [
                {
                    role: "system",
                    content: "You are an expert Next.js and React CI engineer. You are given a Vercel CI stderr build log. Identify the exact file path within the repository that caused the fatal build error. Return ONLY JSON with a `filePath` string relative to the repo root (e.g., 'src/app/page.tsx'). If you cannot identify one, return empty string."
                },
                {
                    role: "user",
                    content: buildLogs.substring(0, 10000) // Cap log size to avoid context overflow
                }
            ]
        });

        const diagnosisJson = JSON.parse(pathDiagnosis.choices[0].message.content || "{}");
        const brokenFilePath = diagnosisJson.filePath;

        if (!brokenFilePath) {
            return NextResponse.json({ error: "Could not isolate the broken file path from logs." }, { status: 400 });
        }

        console.log(`📄 Vercel Guardian: Isolated buggy file -> ${brokenFilePath}`);

        // 4. Fetch the current messy file contents from GitHub
        const currentFileContents = await fetchGitHubFileContents(brokenFilePath);

        // 5. LLM Step 2: Repair the file
        console.log("🛠️ Vercel Guardian: Patching file AST with GPT-4o...");
        const repair = await openai.chat.completions.create({
            model: "gpt-4o",
            response_format: { type: "json_object" },
            messages: [
                {
                    role: "system",
                    content: `You are an expert Next.js/React CI engineer. Diagnose the build error and fix the file. Return ONLY JSON with two keys:\n- 'explanation': Brief technical explanation of the fix.\n- 'fixedContent': The ENTIRE correct file content, ready to be written to disk. Ensure it is complete and not truncated.`
                },
                {
                    role: "user",
                    content: `BUILD ERROR LOGS:\n${buildLogs.substring(0, 5000)}\n\n---\n\nFILE CONTENT (${brokenFilePath}):\n${currentFileContents}`
                }
            ]
        });

        const repairJson = JSON.parse(repair.choices[0].message.content || "{}");
        if (!repairJson.fixedContent) {
           return NextResponse.json({ error: "Agent failed to generate fixed code." }, { status: 500 });
        }

        console.log(`✅ Vercel Guardian: Fix generated -> ${repairJson.explanation}`);

        // 6. Automatically Branch & PR via Octokit
        const shortHash = Math.random().toString(36).substring(2, 8);
        const branchName = `fix/vercel-guardian-${shortHash}`;
        const commitMessage = `fix(${brokenFilePath.split("/").pop()}): auto-patch vercel build failure`;
        
        const prBody = `## Vercel Guardian Auto-Fix 🛡️\n\nA fatal build error occurred on the previous deployment. This PR was automatically generated by the AI Guardian Agent to resolve the issue.\n\n### Diagnosis\n${repairJson.explanation}\n\n### Logs Context\n\`\`\`\n${buildLogs.substring(0, 500)}...\n\`\`\`\n\nPlease review the AST patches before merging this to main.`;

        console.log(`🚀 Vercel Guardian: Opening Pull Request...`);
        const prUrl = await createFixPullRequest(
            brokenFilePath,
            repairJson.fixedContent,
            branchName,
            commitMessage,
            `Fix Build Error in ${brokenFilePath.split("/").pop()}`,
            prBody
        );

        return NextResponse.json({ success: true, prUrl, explanation: repairJson.explanation });

    } catch (error: any) {
        console.error("Vercel Guardian Error:", error);
        return NextResponse.json({ error: "Internal Guardian Error", details: error.message }, { status: 500 });
    }
}
